server:
  port: 8763
eureka:
  instance:
    hostname: ${spring.cloud.client.ip-address}
    instance-id: ${eureka.instance.hostname}:${server.port} #eureka server管理页面显示的服务状态
    preferIpAddress: true                                 #指定通过IP注册,服务集群高可用必须配置,需要ip-address参数一起设置，以免eureka管理页面出现不可用分片提示信息(unavailable-replicas)
    ip-address: ${EUREKA_IP:${eureka.instance.hostname}}  #强制指定eureka的ip地址
  client:
    service-url:
      defaultZone:  http://${eureka.instance.hostname}:8762/eureka/
    fetch-registry: true        #集群时需要强制手动指定，fetch-registry、register-with-eureka都需要设置为true
    register-with-eureka: true  #集群时需要强制手动指定，fetch-registry、register-with-eureka都需要设置为true
    registry-fetch-interval-seconds: 5 #服务器列表信息获取频率，单位秒 默认30秒
spring:
  application:
    name: eureka