server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/,http://localhost:8763/eureka/
    ## 是否将自己注册到eureka
    register-with-eureka: false
spring:
  application:
    name: consumer
